apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: busybox
    image: busybox:latest
    command: ["/bin/sh", "-c", "while true; do echo 'Hello, World!'; sleep 10; done"]
    
